upstream backend {
    server localhost:9003;
}

server {
    listen 80;
    server_name todo.zone.id;

   location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Remove the proxy_cookie_path directive and use proxy_pass_header instead
        proxy_pass_header Set-Cookie;
        proxy_pass_header Cookie;
        
        # Ensure cookies are preserved during proxy
        proxy_redirect off;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}

server {
    if ($host = todo.zone.id) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name todo.zone.id;
    return 404;
}
