apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: todoapp
  labels:
    app: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: todoapp:latest
          imagePullPolicy: Never # for local container image
          ports:
            - containerPort: 12344
          readinessProbe:
            tcpSocket:
              port: 12344
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 12344
            initialDelaySeconds: 3
            failureThreshold: 20
            periodSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      automountServiceAccountToken: false

      