apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: todoapp
  labels:
    app: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          imagePullPolicy: Never
          image: todoapp:latest
          ports:
            - containerPort: 9001
          env:
            - name: APP_NAME
              value: "todoapp"
            - name: HTTP_PORT
              value: "9001"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: ENV
              value: "dev"
            - name: MIGRATION_METHOD
              value: "UP"
            - name: READ_TIMEOUT
              value: "5"
            - name: WRITE_TIMEOUT
              value: "5"
            - name: IDLE_TIMEOUOT
              value: "10"
            - name: DB_HOST
              value: "cwmooldgnk.g6.sqlite.cloud"
            - name: DB_PORT
              value: "8860"
            - name: DB_NAME
              value: "todo"
            - name: DB_API_KEY
              value: ""
            - name: DB_TIMEOUT
              value: "10s"
            - name: DB_MAX_ROWS
              value: "20"
            - name: DB_SECURE_FLAG
              value: "true"
          readinessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9001
            initialDelaySeconds: 20
            failureThreshold: 20
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      automountServiceAccountToken: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoapp-ingress
  labels:
    app.kubernetes.io/name: todoapp-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: todoapp
                port:
                  number: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  selector:
    app: todoapp
  ports:
    - port: 9001
      targetPort: 9001
