apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  labels:
    name: todo-app-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todoapp
            port: 
              number: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: todoapp
  labels:
    app: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: todoapp@latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9001
          env:
            - name: APP_NAME
              value: "todoapp"
            - name: HTTP_PORT
              value: "9001"
            - name: LOG_LEVEL
              value: "9001"
            - name: ENV
              value: "dev"
            - name: MIGRATION_METHOD
              value: "UP"
            - name: READ_TIMEOUT
              value: "5"
            - name: WRITE_TIMEOUT
              value: "5"
            - name: IDLE_TIMEOUOT
              value: "10"
            - name: DB_HOST
              value: ""
            - name: DB_PORT
              value: ""
            - name: DB_NAME
              value: "todo"
            - name: DB_TIMEOUT
              value: "5s"
            - name: DB_API_KEY
              value: ""
            - name: DB_MAX_ROWS
              value: "20"
            - name: DB_SECURE_FLAG            
              value: "true"
          readinessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9001
            initialDelaySeconds: 3
            failureThreshold: 20
            periodSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      automountServiceAccountToken: false
