apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: todoapp
  labels:
    app: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: todoapp:latest
          imagePullPolicy: Never # for local container image
          ports:
            - containerPort: 12344
          resources:
            limits:
              memory: 100Mi #limit memory for a container max of 100 MB
      
      automountServiceAccountToken: false

      readinessProbe:
        tcpSocket:
          port: 12344
        initialDelaySeconds: 15
        periodSeconds: 10
      
      livenessProbe:
        httpGet:
          path: /health
          port: 12344
        initialDelaySeconds: 3
        failureThreshold: 20
        periodSeconds: 3