version: "3.8"

services:
  # PostgreSQL database service
  postgres:
    container_name: postgres_db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-rest-api_app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Go backend service
  todo-backend:
    container_name: todo_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: todo
      DB_USER: postgres
      DB_PASSWORD: root123
      HTTP_PORT: 9003
      FILE_LOGGING_ENABLED: "false"
      LOG_LEVEL: "DEBUG"
      NO_COLOR: "false"
      AUTH_URL: "http://auth-rest-api:9001"
      CORS_ALLOWED_ORIGINS: "http://localhost:8081,http://todo-frontend:80,https://todo.zone.id"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth-rest-api_app-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9003/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  #Svelte frontend service
  todo-frontend:
    container_name: todo_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      VITE_BACKEND_URL: "http://todo-backend:9003"
    depends_on:
      - todo-backend
    networks:
      - auth-rest-api_app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  auth-rest-api_app-network:
    external: true
