openapi: 3.0.3
info:
  title: Todo-API
  description: This is a todo task API which supports creation, updating, deletion of tasks, and user management.
  version: 0.1.0
  contact:
    email: kumarsumitjat298@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: "http://localhost:9001"
paths:
  /tasks:
    get:
      tags:
        - Todo
      summary: Retrieve all tasks
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TodoTask"
        "404":
          description: Task not found

    post:
      tags:
        - Todo
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskInput"
      responses:
        "201":
          description: Task created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoTask"

  /tasks/{taskId}:
    put:
      tags:
        - Todo
      summary: Update a task
      parameters:
        - name: taskID
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoTask"
      responses:
        "200":
          description: Task updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoTask"
        "404":
          description: Task not found

    delete:
      tags:
        - Todo
      summary: Delete a task
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task to delete
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Task deleted
        "404":
          description: Task not found

  /tasks/done/{taskId}:
    patch:
      tags:
        - Todo
      summary: marks the task as done
      parameters:
        - name: taskId
          in : path
          required: true
          description: ID of the task to mark for done
          schema:
            type: string
            format: uuid

      responses:
        "200":
          description: Task is marked as done
        "404":
          description: Task not found

  /login:
    post:
      tags:
        - User
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResp"
        "401":
          description: Invalid username or password
        "404":
          description: Invalid username or password

  /register:
    post:
      tags:
        - User
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User registered
        "400":
          description: Invalid input

components:
  schemas:
    TaskInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string

    TodoTask:
      type: object
      required:
        - title
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        isDone:
          type: boolean
          default: false
        addedAt:
          type: string
          format: date-time
          description: time stamp when task is created
        modifiedAt:
          type: string
          format: date-time
          description: time when the task is updated

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    UserRegister:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    UserResp:
      type: object
      properties:
        id:
          type: string
          format: uuid
        token:
          type: string
        userId:
          type: string
          format: uuid
        expiry:
          type: string
          format: date-time

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
